### PR TITLE
Add performance benchmarks to alert about performance issues

### PR DESCRIPTION
**Pull request by OptimumCode**

### CODE REVIEW

**Comment by krzema12** [comment]
@OptimumCode CI is green! How about we remove the check if we're inside a PR, and see if the report gets uploaded to another repo + plant a performance regression to see what happens?

**Comment by OptimumCode** [comment]
@krzema12 sure, let's do it. But I think after that it would be better to remove the published data from the repository

**Comment by OptimumCode** [comment]
Regarding performance regression: you can see here [what it would look like](https://github.com/OptimumCode/snakeyaml-engine-kmp/pull/1)

**Comment by OptimumCode** [comment]
@krzema12 Results were pushed. https://krzema12.github.io/snakeyaml-engine-kmp-benchmarks/dev/bench/

**Comment by krzema12** [comment]
Works: https://krzema12.github.io/snakeyaml-engine-kmp-benchmarks/dev/bench/

Let me remove this data.

**Review by krzema12 — APPROVED** [review]

**Comment by krzema12** [comment]
@OptimumCode approved, thanks for this 🙇 🚀

**Pull request merged**
