### PR TITLE
use UrlEncoder dependency

### PR DESCRIPTION
**Pull request by aSemy**
### Summary

Migrate UrlEncoder util to the now converted & published UrlEncoder library https://github.com/ethauvin/urlencoder/issues/1

### CODE REVIEW

**Comment by krzema12** [comment]
@aSemy I see the UrlEncoder with your KMP conversion has been published to Maven Central: https://github.com/ethauvin/urlencoder/releases/tag/1.4.0. Is it now fine to continue with this PR? Should I take it over?

**Comment by aSemy** [comment]
Yes, I agree, this PR can be restarted. Feel free to pick it up.

**Comment by krzema12** [comment]
```
ReferencesTest[jvm] > Parsing with aliases may take a lot of time, CPU and memory[jvm] FAILED
```
@aSemy do you recall this issue when you were iterating on the earlier version of this PR?

**Comment by aSemy** [comment]
No sorry that test isn't familiar to me.

**Comment by aSemy** [comment]
The test should be fixed by #127

**Pull request merged**
